angular.module('beertube.video').service('Video', function() {
  video = this;
  video.mostViewed = function (limit) {
    limit = limit || 5;
    all_videos_sorted = video.all().sort(function(video1, video2) {
      return video1.view - video2.view;
    });
    return all_videos_sorted.slice(0, limit);
  };

  video.all = function() {
    return [
      {
        id: 1,
        title: "Hugh Jackman Is Back To Begin His Final Journey As Old Wolverine In The First \"Logan\" Trailer",
        description: "It doesn't look like a super hero movie at all. It's all about Logan's story.",
        url: "https://youtu.be/Div0iP65aZo",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 6268517,
        point: 12356,
      },
      {
        id: 2,
        title: "Sexy Girl Has A Blast While Riding On 1200HP Camaro",
        description: "She is ridiculously cute.﻿",
        url: "https://youtu.be/UfLjm6kqpeE",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 6268517,
        point: 12356,
      },
      {
        id: 3,
        title: "New \"Resident Evil: The Final Chapter\" International Trailer Takes Alice On An Insane Ride",
        description: "Looks like it's gonna be the best Resident Evil movie.",
        url: "https://youtu.be/_h6t_Ee5r68",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 62617,
        point: 156,
      },
      {
        id: 4,
        title: "Hot Korean Girls Perform A Sexy Dance For The Song \"Hello Hello\" In 360° Video",
        description: "It needs a zoom feature!",
        url: "https://youtu.be/DRe41iTmwws",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 26851,
        point: 356,
      },
      {
        id: 5,
        title: "\"Store Cat Food vs Homemade\" What Will The Cat Choose?",
        description: "That is one very patient cat.",
        url: "https://youtu.be/cofNVuXgjsA",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 8517,
        point: 456,
      },
      {
        id: 6,
        title: "Sexy And Hot Moments In Sport To Prepare You For Rio 2016 Olympics",
        description: "Who would ever forget Michelle Jenneke's famous warm up dance?",
        url: "https://youtu.be/Div0iP65aZo",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 12268517,
        point: 12356,
      },
      {
        id: 7,
        title: "It's True: Everyone Walking Around With A Phone Is Playing \"Pokemon Go\"",
        description: "YouTuber Casey Neistat goes outside and asks people on their phones if they were playing Pokémon Go. The answer was always \"yes.\" Never have you seen the world so captivated by a game before.",
        url: "https://youtu.be/jOeZBW9Lwos",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 78517,
        point: 421,
      },
      {
        id: 8,
        title: "Naked Artist Carries A Baby To Art Museum To See \“How Little Abstraction Can Art Tolerate\"",
        description: "Milo Moire the artist has taken art to extreme again.",
        url: "https://youtu.be/7JbbRpZTwYY",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 1922519,
        point: 4295,
      },
      {
        id: 9,
        title: "Andrew Garfield Stars In Mel Gibson-Directed War Film \"Hacksaw Ridge\" As A War Hero",
        description: "This is thrilling. We need Mel Gibson to direct some more medieval epics.﻿",
        url: "https://youtu.be/s2-1hz1juBI",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 5173512,
        point: 356,
      },
      {
        id: 10,
        title: "Here Are The Cutest And Funniest Covers Of Japan's Crazy Song \"Pen-Pineapple-Apple-Pen\"",
        description: "It makes no sense, but it will certainly get stuck in your head!",
        url: "https://youtu.be/2527yFt4wRU",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 4268517,
        point: 12356,
      },
      {
        id: 11,
        title: "Watch Hot Bikini Girls Enjoy The World's Biggest Lube Slide",
        description: "That's a slippery slope.",
        url: "https://youtu.be/oAUr4fW0w-c",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 8162541,
        point: 7356,
      },
      {
        id: 12,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 13,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 14,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 15,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 16,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 17,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 18,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 19,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 20,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 21,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 22,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 23,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 24,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 25,
        title: "Japanese Girl Removes Nasal Hair In The Most Unusual Way",
        description: "OMG... I can feel the second hand pain.",
        url: "https://youtu.be/jHOWNfhoT7I",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 462517,
        point: 142,
      },
      {
        id: 26,
        title: "Sexy And Hot Moments In Sport To Prepare You For Rio 2016 Olympics",
        description: "Who would ever forget Michelle Jenneke's famous warm up dance?",
        url: "https://youtu.be/Div0iP65aZo",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 12268517,
        point: 12356,
      },
      {
        id: 27,
        title: "It's True: Everyone Walking Around With A Phone Is Playing \"Pokemon Go\"",
        description: "YouTuber Casey Neistat goes outside and asks people on their phones if they were playing Pokémon Go. The answer was always \"yes.\" Never have you seen the world so captivated by a game before.",
        url: "https://youtu.be/jOeZBW9Lwos",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 78517,
        point: 421,
      },
      {
        id: 28,
        title: "Naked Artist Carries A Baby To Art Museum To See \“How Little Abstraction Can Art Tolerate\"",
        description: "Milo Moire the artist has taken art to extreme again.",
        url: "https://youtu.be/7JbbRpZTwYY",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 1922519,
        point: 4295,
      },
      {
        id: 29,
        title: "Andrew Garfield Stars In Mel Gibson-Directed War Film \"Hacksaw Ridge\" As A War Hero",
        description: "This is thrilling. We need Mel Gibson to direct some more medieval epics.﻿",
        url: "https://youtu.be/s2-1hz1juBI",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 5173512,
        point: 356,
      },
      {
        id: 30,
        title: "Here Are The Cutest And Funniest Covers Of Japan's Crazy Song \"Pen-Pineapple-Apple-Pen\"",
        description: "It makes no sense, but it will certainly get stuck in your head!",
        url: "https://youtu.be/2527yFt4wRU",
        thumbnails: {hq: "https://i.ytimg.com/vi/92XVwY54h5k/hqdefault.jpg",
                     mq: "https://i.ytimg.com/vi/92XVwY54h5k/mqdefault.jpg"},
        view: 4268517,
        point: 12356,
      }
    ];
  };
});
